pipeline:
  prep-release:
    image: alpine:latest
    commands:
      - mkdir -p modAchievementStatTrak
      - mv content/ modAchievementStatTrak/
      - apk update
      - apk add zip
      - zip -r modAchievementStatTrak.zip modAchievementStatTrak/
    when:
      event: tag

  release-stable:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "*.zip"
      draft: true
    when:
      event: tag