pipeline:
  prep-release:
    image: alpine:latest
    commands:
      - apk update
      - apk add zip
      - zip -r StatTrak.zip dlc mods bin
    when:
      event: tag

  release-stable:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "*.zip"
      draft: true
    when:
      event: tag