on: [push]

jobs:
  encode:
    runs-on: ubuntu-latest
    name: Encode
    steps:
      - uses: actions/checkout@v3
      - name: Encode
        uses: adawesomeguy/w3strings-action@v1.1
        with:
          csv-path: 'strings/csv/en.w3strings.csv'
          id-space: 6720
          out-dir: 'dlc/dlcStatTrak/content'
          language: 'en'
      - uses: endbug/add-and-commit@v8
        with:
            message: '[CI] Update W3Strings'
